// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: model/proto/log/log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestReceivedProto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantID string   `protobuf:"bytes,1,opt,name=TenantID,proto3" json:"TenantID,omitempty"`
	Streams  []*Strms `protobuf:"bytes,2,rep,name=Streams,proto3" json:"Streams,omitempty"`
}

func (x *RequestReceivedProto) Reset() {
	*x = RequestReceivedProto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_log_log_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReceivedProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReceivedProto) ProtoMessage() {}

func (x *RequestReceivedProto) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_log_log_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReceivedProto.ProtoReflect.Descriptor instead.
func (*RequestReceivedProto) Descriptor() ([]byte, []int) {
	return file_model_proto_log_log_proto_rawDescGZIP(), []int{0}
}

func (x *RequestReceivedProto) GetTenantID() string {
	if x != nil {
		return x.TenantID
	}
	return ""
}

func (x *RequestReceivedProto) GetStreams() []*Strms {
	if x != nil {
		return x.Streams
	}
	return nil
}

type Strms struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stream      map[string]string `protobuf:"bytes,1,rep,name=Stream,proto3" json:"Stream,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TwoDimValue []*OneDimValue    `protobuf:"bytes,2,rep,name=TwoDimValue,proto3" json:"TwoDimValue,omitempty"`
}

func (x *Strms) Reset() {
	*x = Strms{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_log_log_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Strms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Strms) ProtoMessage() {}

func (x *Strms) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_log_log_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Strms.ProtoReflect.Descriptor instead.
func (*Strms) Descriptor() ([]byte, []int) {
	return file_model_proto_log_log_proto_rawDescGZIP(), []int{1}
}

func (x *Strms) GetStream() map[string]string {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *Strms) GetTwoDimValue() []*OneDimValue {
	if x != nil {
		return x.TwoDimValue
	}
	return nil
}

type OneDimValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValTime string `protobuf:"bytes,1,opt,name=valTime,proto3" json:"valTime,omitempty"`
	ValMsg  string `protobuf:"bytes,2,opt,name=valMsg,proto3" json:"valMsg,omitempty"`
}

func (x *OneDimValue) Reset() {
	*x = OneDimValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_log_log_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneDimValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneDimValue) ProtoMessage() {}

func (x *OneDimValue) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_log_log_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneDimValue.ProtoReflect.Descriptor instead.
func (*OneDimValue) Descriptor() ([]byte, []int) {
	return file_model_proto_log_log_proto_rawDescGZIP(), []int{2}
}

func (x *OneDimValue) GetValTime() string {
	if x != nil {
		return x.ValTime
	}
	return ""
}

func (x *OneDimValue) GetValMsg() string {
	if x != nil {
		return x.ValMsg
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_proto_log_log_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_log_log_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_model_proto_log_log_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_model_proto_log_log_proto protoreflect.FileDescriptor

var file_model_proto_log_log_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f,
	0x67, 0x2f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x07, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x72, 0x6d, 0x73, 0x52, 0x07, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x22, 0xaa,
	0x01, 0x0a, 0x05, 0x53, 0x74, 0x72, 0x6d, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x6d, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x34, 0x0a, 0x0b, 0x54, 0x77,
	0x6f, 0x44, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x6e, 0x65, 0x44, 0x69, 0x6d, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x0b, 0x54, 0x77, 0x6f, 0x44, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x1a, 0x39, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3f, 0x0a, 0x0b, 0x4f,
	0x6e, 0x65, 0x44, 0x69, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x61, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x32, 0x53, 0x0a, 0x0f, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x49, 0x6e, 0x67,
	0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_proto_log_log_proto_rawDescOnce sync.Once
	file_model_proto_log_log_proto_rawDescData = file_model_proto_log_log_proto_rawDesc
)

func file_model_proto_log_log_proto_rawDescGZIP() []byte {
	file_model_proto_log_log_proto_rawDescOnce.Do(func() {
		file_model_proto_log_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_log_log_proto_rawDescData)
	})
	return file_model_proto_log_log_proto_rawDescData
}

var file_model_proto_log_log_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_proto_log_log_proto_goTypes = []interface{}{
	(*RequestReceivedProto)(nil), // 0: proto.RequestReceivedProto
	(*Strms)(nil),                // 1: proto.Strms
	(*OneDimValue)(nil),          // 2: proto.OneDimValue
	(*Response)(nil),             // 3: proto.Response
	nil,                          // 4: proto.Strms.StreamEntry
}
var file_model_proto_log_log_proto_depIdxs = []int32{
	1, // 0: proto.RequestReceivedProto.Streams:type_name -> proto.Strms
	4, // 1: proto.Strms.Stream:type_name -> proto.Strms.StreamEntry
	2, // 2: proto.Strms.TwoDimValue:type_name -> proto.OneDimValue
	0, // 3: proto.IngesterService.PushToIngester:input_type -> proto.RequestReceivedProto
	3, // 4: proto.IngesterService.PushToIngester:output_type -> proto.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_proto_log_log_proto_init() }
func file_model_proto_log_log_proto_init() {
	if File_model_proto_log_log_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_proto_log_log_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestReceivedProto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_log_log_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Strms); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_log_log_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneDimValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_proto_log_log_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_log_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_log_log_proto_goTypes,
		DependencyIndexes: file_model_proto_log_log_proto_depIdxs,
		MessageInfos:      file_model_proto_log_log_proto_msgTypes,
	}.Build()
	File_model_proto_log_log_proto = out.File
	file_model_proto_log_log_proto_rawDesc = nil
	file_model_proto_log_log_proto_goTypes = nil
	file_model_proto_log_log_proto_depIdxs = nil
}
